---
title: "AntechinusSliding"
author: "PViacava"
date: "16/03/2020"
output: html_document
---
title: "Antechinus_sliding"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = '../Viacavaetal_Antechinus/Data', echo = TRUE)



library(Morpho)
library(rgl)
library(Rvcg)
library(geomorph)
library(abind)


```

```{r load data}

## import template mesh and landmark set

subtropicus.holo<-file2mesh('C:/Users/pietro/Desktop/Pietro/Projects/Viacavaetal_Antechinus/Data/3Dmodels/AntechinusAll3Dmodels/J17407.ply',readcol=F,clean=T)
subtropicus.p<-(read.csv('C:/Users/pietro/Desktop/Pietro/Projects/Viacavaetal_Antechinus/Data/Templatecoords.csv', header = F))

dim(subtropicus.p) 
rownames(subtropicus.p)<-subtropicus.p$V1 
subtropicus.p1 <- subtropicus.p[,-1]
dim(subtropicus.p1) #412 landmarks, 3 dimensions

#reordering landmarks: curves first, patches second and curves last
template.pf <- subtropicus.p1[1:82,]
template.pc <- subtropicus.p1[83:267,]
template.pp <- subtropicus.p1[268:412,]
template.p <- rbind(template.pf, template.pc, template.pp)
template.p1 <- template.p[-c(83,96,131:138,152:153,158:163,167:168,173:182,232:233,244:247),]

#VW trying to get this into an array - first turn each column into a vector
V2 <-template.p1$V2
V3 <-template.p1$V3
V4 <- template.p1$V4

template_array <- array(c(V2, V3, V4), dim = c(376, 3, 1))


#plot landmarks on mesh to check if they correspond well
shade3d(subtropicus.holo,col = 8)
spheres3d(template_array[1:82,,],radius = 0.2,col = 1)#fixed. nb of landmarks = (  z-1)/3  82
spheres3d(template_array[83:231,,],radius = 0.1,col = 2) #curves 185
spheres3d(template_array[232:376,,],radius = 0.1,col = 3) #patches 145

text3d(template_array[1:376,,], texts = c(1:376), asp = FALSE, cex = 1, col="blue", pos = 3) #plot number of landmarks to check ordering

#import landmark sets for all specimens
LMcoords <- t(read.csv('C:/Users/pietro/Desktop/Pietro/Projects/Viacavaetal_Antechinus/Data/Antechinus_LMcoords.csv', header = T, row.names = 1))
dim(LMcoords)
Ants <- arrayspecs(LMcoords, 82, 3) #convert into array
dim(Ants)
Ahead <- head(dimnames(Ants))[3]
```

```{r template creation}

# specify fixed landmarks of template specimen in a matrix
fixed<-as.matrix(template_array[c(1:82),,])

# specify semilandmarks of template specimen in a matrix
patch<-as.matrix(template_array[c(83:376),,])
rownames(patch)<-c(1:294)


#Atlas creation
Atlas<-createAtlas(subtropicus.holo,landmarks = fixed, patch = patch, patchCurves = list(c(1:3, c(4:6), c(7:9), c(10:12), c(13:20), c(21:23), c(24:26), c(27:29), c(30:32), c(33:36), c(37:40), c(41:43), c(44:46), c(47:51), c(52:56), c(57:59), c(60:63), c(64:66), c(67:70), c(71:75), c(76:78), c(79:81), c(82:85), c(86:89), c(90:93), c(94:97), c(98:100), c(101:103), c(104:106), c(107:111), c(112:114), c(115:119), c(120:124), c(125:129), c(130:132), c(133:135), c(136:138), c(139:146), c(147:149), c(150:294))))

#Atlas plot 
cols<-c("black","red","green","blue")
plotAtlas(Atlas, pt.size=0.2, point = "s", legend = TRUE, cols = cols)

#CHECK THIS: CURVES ONLY ON ATLAS BUT NO PATCH SEMILMS

```


```{r semilandmark placement}

knitr::opts_knit$set(root.dir = 'Viacavaetal_Antechinus/Data/3Dmodels/AntechinusAll3Dmodels/', echo = TRUE)

#Folder with all meshes
Folder <- "../Data/3Dmodels/AntechinusAll3Dmodels"

#Navigate to folder with the subsample of ply files
Plylist <- sub(".ply", "", list.files(Folder))



#extract the coordinates that correspond to the ply files - note the dimnames and the ply file names need to be identical
#match ply file names with data names and reorder

match(Plylist, dimnames(Ants)[[3]])

Plylist==dimnames(Ants)[[3]]

data_reorder<-Ants[, , match(Plylist, dimnames(Ants)[[3]])]

names_reorder<-dimnames(data_reorder)[[3]]
match(names_reorder, Plylist)

dimnames(data_reorder)[[3]] == Plylist

setwd("C:/Users/pietro/Desktop/Pietro/Projects/Viacavaetal_Antechinus/Data/3Dmodels/AntechinusAll3Dmodels/") #does not work with Rmd, run separately

nma<-list.files(path="../Data/3Dmodels/AntechinusAll3Dmodels")
listo<-do.call(list,lapply(nma,function(x) file2mesh(x,readcol=F,clean=T)))

#semilandmark placement in all specimenes

lmplacement<-placePatch(Atlas, data_reorder, path="../Data/3Dmodels/AntechinusAll3Dmodels/", inflate=0.5) # use ray=TRUE for projection along surface normals instead of closest point???

#check good placement of semilandmarks in all specimens
checkLM(lmplacement, path = "../Data/3Dmodels/AntechinusAll3Dmodels/", atlas=Atlas, point = "s", pt.size = 0.2)

#CHECKING IF ORDER OF LANDMARKS IS FUCKED UP AND IF THAT'S ALSO FUCKING UP THE LANDMARK PLACEMENT ABOVE

CM16483<-file2mesh('../Data/3Dmodels/AntechinusAll3Dmodels/CM16483.ply',readcol=F,clean=T)
shade3d(CM16483, col = 8)
spheres3d(Ants[,,1],radius = 0.2,col = 1)
text3d(Ants[,,1], texts = c(1:82), asp = FALSE, cex = 2, col="blue", pos = 3)

```

```{r checking placement and making curves equidistant}

setwd("../Data/3Dmodels/AntechinusAll3Dmodels")

provo<-placePatch(Atlas,data_reorder,path="../Data/3Dmodels/AntechinusAll3Dmodels/",
                  inflate=0.5)


mfrow3d(2,3,sharedMouse = T)
shade3d(subtropicus.holo,col=8)
spheres3d(template_array[1:82,,],radius = 0.2,col = 1)#fixed. nb of landmarks = (  z-1)/3  82
spheres3d(template_array[83:231,,],radius = 0.1,col = 2) #curves 185
spheres3d(template_array[232:376,,],radius = 0.1,col = 3)

for(i in 1:dim(data_reorder)[[3]]){
next3d()
shade3d(listo[[i]],col=8)
spheres3d(provo[1:82,,i],radius=0.2,col=1)
spheres3d(provo[83:231,,i],radius=0.2,col=2)
spheres3d(provo[232:376,,i],radius=0.2,col=3)
}

equi<-matrix(NA,ncol =3)
disto<-NULL
for(i in 1:dim(provo)[[3]]){
ccc<-provo[221:228,,i]
disto[i]<-list(equidistantCurve(ccc,iterations=10,increment=6,smoothit=4,mesh=listo[[i]]))
equi<-array(as.numeric(unlist(disto)),dim=dim(provo[221:228,,]))
}

new.prov<-bindArr(provo[1:220,,],equi,provo[229:376,,],along=1)


newi<-new.prov[-c(115:122,142:145,149:152),,]


mfrow3d(2,3,sharedMouse = T)
mfrow3d(1,2,sharedMouse = T)


shade3d(tempmesh,col=8)
spheres3d(templa[1:82,],radius=0.2,col=1)
spheres3d(templa[83:231,],radius=0.2,col=2)
spheres3d(templa[232:376,],radius=0.2,col=3)

for(i in 1:dim(new.prov)[[3]]){
  
  next3d()
  shade3d(listo[[i]],col=8)
  spheres3d(new.prov[1:82,,i],radius=0.2,col=1)
  spheres3d(new.prov[83:231,,i],radius=0.1,col=2)
  spheres3d(new.prov[232:376,,i],radius=0.1,col=3)
  
}

i=2


palle<-bindArr(new.prov[1:82,,],equi2,along=1)



shade3d(meshi,col=8)
spheres3d(newi[1:82,,2],radius=0.2,col=1)
spheres3d(newi[83:215,,2],radius=0.2,col=2)
spheres3d(newi[216:360,,2],radius=0.2,col=3)


meshi<-vcgQEdecim(listo[[2]],percent = 0.05)

shade3d(meshi,col=8)

writeWebGL("new.html")





```